Automerge repo announcement post
automerge/old-automerge-website pull request #44
Opened 2023-11-04 13:17 UTC by alexjg

2023-11-04 19:24 UTC, heckj requested changes
I ran through the post with an eye towards:
- typos (there were multiple instances of stuttering/replication in the wording, I suspect a copy/paste or quick-editing error along the way)
- direct instruction and description of code snippets
- consistency in referencing Automerge (a little uncertain on `Automerge Repo` and `automerge-repo`)
- tightening up the sentences to remove redundancy or passive voice, while trying to avoid touching anything that would impact the voice of the narrator.

2023-11-04 19:24 UTC, heckj commented on blog/2023-10-19-automerge-repo.md
> +The most obvious problem in local-first software is how to combine work from different users either in real-time (think GGoogle DDocs) or asynchronously (think GGit).. CRDTs were developed to solve t
fixing some stuttering caps

```suggestion
The most obvious problem in local-first software is how to combine work from different users either in real-time (think Google Docs) or asynchronously (think Git).. CRDTs were developed to solve this problem.
```

2023-11-04 19:24 UTC, heckj commented on blog/2023-10-19-automerge-repo.md
> +Our new library, `automerge-repo`, allows a developer to start building local-first applications with Automerge right away by combining the collaboration engine of the core Automerge library with ext
Felt like Automerge was being repeated unnecessarily:

```suggestion
Our new library, `automerge-repo`, allows a developer to start building local-first applications with Automerge right away by combining the collaboration engine of the core library with extensible networking and storage systems.
```

2023-11-04 19:24 UTC, heckj commented on blog/2023-10-19-automerge-repo.md
> +For those new to this idea, local-first applications are a way of building software that combines the benefits of the current cloud model with robust support for real-time collaboration and offline u
Another stutter (copy/paste issue from another editor?)

```suggestion
For those new to this idea, local-first applications are a way of building software that combines the benefits of the current cloud model with robust support for real-time collaboration and offline use. You can read more about the motivation for local-first applications [in our essay](https://inkandswitch.com/local-first/), or you can watch a [talk introducing the idea](<youtube link to malaga talk>).
```

2023-11-04 19:24 UTC, heckj commented on blog/2023-10-19-automerge-repo.md
> +If you've been intimidated by the idea of integrating Automerge into your application because of all the extra busywork implied, this library is for you. You can simply create a repo, point it to a s
tightened up the sentence a smidge
```suggestion
If you've been intimidated by the idea of integrating Automerge into your application because of this implied  busywork, this library is for you. You can simply create a repo, point it to a sync server, and get to work on your app.
```

2023-11-04 19:24 UTC, heckj commented on blog/2023-10-19-automerge-repo.md
> +Let's start by taking a look at a simplified example of how Automerge Repo works. To begin, we create and configure a repository for Automerge documents.
Direct instruction tends to resolve better to a variety of speakers over "we", especially for uncertain newcomers. It tries to be inclusive, but tends to end up distancing some readers who are new and uncertain.

```suggestion
Let's start by taking a look at a simplified example of how Automerge Repo works. To begin, create and configure a repository for Automerge documents.
```

2023-11-04 19:24 UTC, heckj commented on blog/2023-10-19-automerge-repo.md
> +Here, we're creating a Repo and adding a storage and network adapter to it. This tells Automerge Repo to store all changes in an IndexedDB table called `automerge-demo` and to synchronize documents w
```suggestion
The code above creates a Repo and adds a storage and network adapter to it. This tells Automerge Repo to store all changes in an IndexedDB table called `automerge-demo` and to synchronize documents with the peer at `sync.automerge.org`. The library is designed to support a wide variety of network transports, and includes a simple client/server websocket out of the box. There are already members of the community adding support for other transports such as WebRTC. 
```

2023-11-04 19:24 UTC, heckj commented on blog/2023-10-19-automerge-repo.md
> +In this example we're connecting to the public test server hosted by the automerge team, but you can also run your own sync server. In fact, our [sync server](linktosyncservercode) runs almost the sa
```suggestion
The next code snippet connects to the public test server, hosted by the Automerge team. You can also run your own sync server. In fact, our [sync server](linktosyncservercode) runs similar code to the example above, with different network and storage adapters.
```

2023-11-04 19:24 UTC, heckj commented on blog/2023-10-19-automerge-repo.md
> +Next, let's create a document and make some changes to it:
```suggestion
Next, create a document and make some changes to it:
```

2023-11-04 19:24 UTC, heckj commented on blog/2023-10-19-automerge-repo.md
> +```
Was this code intended to be indented where the others aren't? Wasn't entirely sure...

2023-11-04 19:24 UTC, heckj commented on blog/2023-10-19-automerge-repo.md
> +This prints a URL. On another computer or in another browser, you can try and load this document using the same URL:
```suggestion
The snippet above prints the URL of the created document. On another computer, or in another browser, you can load this document using the same URL:
```

2023-11-04 19:24 UTC, heckj commented on blog/2023-10-19-automerge-repo.md
> +You create a repo by initializing it with an optional storage plugin (not required) and any number of network adapters. These are the options for initializing a repo:
`optional` and `(not required)` are redundant

```suggestion
Create a repo by initializing it with an optional storage plugin and any number of network adapters. These are the options for initializing a repo:
```

2023-11-04 19:24 UTC, heckj commented on blog/2023-10-19-automerge-repo.md
> +A `DocHandle` is a reference to an automerge document which is being synced and stored by the `Repo` from which you obtained the handle. This means that any changes you make to the document will be s
```suggestion
A `DocHandle` is a reference to an Automerge document which is being synced and stored by the `Repo` from which you obtained the handle. Automerge-repo saves any changes you make to the document to storage and syncs with peers.  You listen for changes received over the network.
```

2023-11-04 19:24 UTC, heckj commented on blog/2023-10-19-automerge-repo.md
> +`DocHandle`s have a `.url` property. This is a string of the form `automerge:<base58 encoded bytes>` which uniquely identifies a document. Once you have a URL you can use it to request the document f
```suggestion
`DocHandle`s has a `.url` property. This is a string of the form `automerge:<base58 encoded bytes>` which uniquely identifies a document. Once you have a URL you can use it to request the document from other peers.
```

2023-11-04 19:24 UTC, heckj commented on blog/2023-10-19-automerge-repo.md
> +`DocHandle.on("change")` is called whenever the document is modified - either due to a local change or a sync message being received.
```suggestion
`automerge-repo` calls `DocHandle.on("change")` whenever the document is modified - either due to a local change or a sync message being received.
```

2023-11-04 19:24 UTC, heckj commented on blog/2023-10-19-automerge-repo.md
> +`automerge-repo` provides a set of primitives which are widely applicable, this means we have been able to build integrations with common toolkits on top of it (and you can too).
```suggestion
`automerge-repo` provides a set of primitives which are widely applicable. The Automerge team has built integrations with common toolkits on top of it (and you can too).
```

2023-11-04 19:24 UTC, heckj commented on blog/2023-10-19-automerge-repo.md
> +We'd love to help you make automerge work in your favorite development environment, reach out to us on Github or via the Slack.
Where on GitHub? (recommend adding a specific link - maybe `https://github.com/automerge/automerge-repo/issues`?) Likewise, `Slack` should be/include a link to the invite/access to get there.

2023-11-04 19:24 UTC, heckj commented on blog/2023-10-19-automerge-repo.md
> +A network adapter represents a way of connecting to other peers. Network adapters raise events when a new peer is discovered or when a message is recieved and implement a `send` method for transmitti
```suggestion
A network adapter represents a way of connecting to other peers. Network adapters raise events when a new peer is discovered or when a message is recieved and implement a `send` method for transmitting messages to another peer. `automerge-repo` assumes a reliable, in-order transport for each peer; so as long as you can provide this, you can implement an adapter. You could implement an adapter for BLE for example.
```

2023-11-04 20:39 UTC, ept commented
@heckj Looks like we made a bunch of changes concurrently (I just committed a copyediting pass to this branch). I'll let @alexjg resolve the conflicts.

BTW, those duplicated strings in a few places are because I first made those edits in the Automerge doc in one browser, but then they didn't show up in another browser so I made the same edits again in the other browser. Turns out those edits did actually sync to the server, and so they got applied twice 😭

2023-11-04 21:08 UTC, heckj commented
Mine were un-asked-for suggestions, so feel free to consider or dump any remaining bits as they make sense, or I'd be happy to take another pass after more edits if they were useful, but too early.

2023-11-06 18:38 UTC, heckj requested changes
I whipped out my "passive voice" hammer and liberally applied it. Most of the updates (I hope) are easy "yeah, apply that!" links in the PR that hopefully won't be too controversial. Please **DO** check to make sure I haven't changed meaning or asserted something incorrectly while I was doing that. I tried hard not to.

I also moved any of the "we/us" language in the example flow to direct instruction, especially with the usage of "we" later in the content referring to the Automerge team.

There was a note added about "hey, this stuff's NOT private, and don't count on it for reliability" that I think needs to shift down a bit to make more narrative sense, but that's not something I can suggest with Github's "suggest a replacement" function.

2023-11-06 18:38 UTC, heckj commented on blog/2023-11-06-automerge-repo.md
> +For those new to this idea: local-first applications are a way of building software that allows both real-time collaboration (think Google Docs) and offline working (think Git). They work by storing
```suggestion
For those new to this idea: local-first applications are a way of building software that allows both real-time collaboration (think Google Docs) and offline working (think Git). They work by storing the user's data locally, on their own device, and syncing it with collaborators in the background. You can read more about the motivation for local-first software [in our essay](https://inkandswitch.com/local-first/), or watch a [talk introducing the idea](https://www.youtube.com/watch?v=PHz17gwiOc8).
```

2023-11-06 18:38 UTC, heckj commented on blog/2023-11-06-automerge-repo.md
> +A challenge in local-first software is how to merge edits that were made independently on different devices, and [CRDTs](https://crdt.tech/) were developed to solve this problem. Automerge is a CRDT
```suggestion
A challenge in local-first software is how to merge edits that were made independently on different devices, and [CRDTs](https://crdt.tech/) were developed to solve this problem. Automerge is a fairly mature CRDT implementation. In fact, we wrote this blog post using it! The API is quite low-level though, and Automerge-Core has no opinion about how networking or storage should be done. Often, the first thing developers ask after discovering Automerge was how to connect it into an actual application.
```

2023-11-06 18:38 UTC, heckj commented on blog/2023-11-06-automerge-repo.md
> +Our new library, `automerge-repo`, extends the collaboration engine of Automerge-Core with networking and storage adapters, and it also provides integrations with React and other UI frameworks. This
The second sentence here runs a bit long for an introduction, and I was tempted to suggest pruning out `, what network format to use` as well - but GitHub doesn't have a way to make this a more granular change option since it's all on "one line" ;-) I left it in for now, but I think the sentence reads better without, with the idea that this should be highlighting the "batteries included means easy" rather than getting lured into listing the adapters currently available. 


```suggestion
Our new library, `automerge-repo`, extends the collaboration engine of Automerge-Core with networking and storage adapters, and provides integrations with React and other UI frameworks. You can get to building your app straight away by taking advantage of default implementations that solve common problems such as how to send binary data over a WebSocket, how often to send synchronization messages, what network format to use, or how to store data in places like the browser's IndexedDB or on the filesystem.
```

2023-11-06 18:38 UTC, heckj commented on blog/2023-11-06-automerge-repo.md
> +If you've been intimidated by the idea of integrating Automerge into your application because of all the extra busywork involved, this library is for you. Now you can simply create a repo, point it t
```suggestion
If you've been intimidated by the effort of integrating Automerge into your application because of these choices, this library is for you. Now you can simply create a repo, point it to a sync server, and get to work on your app.
```

2023-11-06 18:38 UTC, heckj commented on blog/2023-11-06-automerge-repo.md
> +If you've been intimidated by the idea of integrating Automerge into your application because of all the extra busywork involved, this library is for you. Now you can simply create a repo, point it t
When I'm reading this, we start by talking about "local first!" and then we end this section with the sentence "Now you can simply create a repo, point it to a sync server, and get to work on your app." - which seems antithetical to the idea of local-first since we're talking about a sync-server. The sync-server is primarily about ease of collaboration that is frequently requested, so I think this might be better as something akin to:

"Now you can create a repo locally, have convenient access to a sync-server for collaboration, and get to work on your app."

Not entirely happy with that sentence, as it feels to heavy, but it resolves some of the discordance that I read summing this together.

2023-11-06 18:38 UTC, heckj commented on blog/2023-11-06-automerge-repo.md
> +Let's start by taking a look at a simple example of how `automerge-repo` works. To begin, we create and configure a repository for Automerge documents.
```suggestion
Let's start by taking a look at a simple example of how `automerge-repo` works. To begin, create and configure a repository for Automerge documents.
```

2023-11-06 18:38 UTC, heckj commented on blog/2023-11-06-automerge-repo.md
> +The sync server at sync.automerge.org is publicly available, but also consequently not very reliable. You should assume that data will disappear arbitrarily and that the server might just fall over.
```suggestion
The Automerge project provides a public sync server for you to experiment with `sync.automerge.org`. This is not a private instance, and as an experimental service has no reliability or data safety guarantees. Basically, it's good for demos and prototyping, but run your own sync server for production uses.
```

2023-11-06 18:38 UTC, heckj commented on blog/2023-11-06-automerge-repo.md
> +Here, we're creating a Repo and adding a storage and network adapter to it. This tells `automerge-repo` to store all changes in an IndexedDB table called `automerge-demo` and to synchronize documents
Move this above the **note** paragraph above, to keep it more localized to the code snippet that it's describing.

```suggestion
The code in the example above creates a repository and adds a storage and network adapter to it. It tells `automerge-repo` to store all changes in an IndexedDB table called `automerge-demo` and to synchronize documents with the WebSocket server at `sync.automerge.org`. The library is designed to support a wide variety of network transports, and we include a simple client/server WebSocket adapter out of the box. Members of the community are already adding support for other transports, such as WebRTC.
```

2023-11-06 18:38 UTC, heckj commented on blog/2023-11-06-automerge-repo.md
> +In this example we're connecting to the public test server hosted by the Automerge team, but you can also run your own sync server. In fact, our [sync server](https://github.com/automerge/automerge-r
I recommend putting the Note about experimental status, data wiping, etc - underneath this sentence

2023-11-06 18:38 UTC, heckj commented on blog/2023-11-06-automerge-repo.md
> +Next, let's create a document and make some changes to it:
```suggestion
Next, create a document and make some changes to it:
```

2023-11-06 18:38 UTC, heckj commented on blog/2023-11-06-automerge-repo.md
> +This prints a URL. On another computer or in another browser, you can load this document using the same URL:
```suggestion
The code logs a URL to the document you created. On another computer, or in another browser, you could load this document using the same URL, as shown below:
```

2023-11-06 18:38 UTC, heckj commented on blog/2023-11-06-automerge-repo.md
> +You create a repo by initializing it with an optional storage plugin and any number of network adapters. These are the options for initializing a repo:
```suggestion
Create a repo by initializing it with an optional storage plugin and any number of network adapters. These are the options for initializing a repo:
```

2023-11-06 18:38 UTC, heckj commented on blog/2023-11-06-automerge-repo.md
> +Even though we call each device a "peer", `automerge-repo` actually works with both client-server transports and peer-to-peer networks.
```suggestion
Don't let the usage of "peer" confuse you into thinking this is limited to peer to peer connectivity, `automerge-repo` works with both client-server and peer-to-peer network transports.
```

2023-11-06 18:38 UTC, heckj commented on blog/2023-11-06-automerge-repo.md
> +A `DocHandle` is a reference to an Automerge document that is synced and stored by the `Repo` from which you obtained the handle. This means that any changes you make to the document will be saved to
```suggestion
A `DocHandle` is a reference to an Automerge document that a `Repo` syncs and stores . The `Repo` instance saves any changes you make to the document and syncs with connected peers. Likewise, you can listen over the network for to a `Repo` for any changes it received.
```

2023-11-06 18:38 UTC, heckj commented on blog/2023-11-06-automerge-repo.md
> +Each `DocHandle` has a `.url` property. This is a string of the form `automerge:<base58 encoded bytes>`, which uniquely identifies a document. Once you have a URL you can use it to request the docume
```suggestion
Each `DocHandle` has a `.url` property. This is a string which uniquely identifies a document in the form `automerge:<base58 encoded bytes>`. Once you have a URL you can use it to request the document from other peers.
```

2023-11-06 18:38 UTC, heckj commented on blog/2023-11-06-automerge-repo.md
> +These two methods return the current state of the document. The difference is that `doc()` is an async method that resolves when the document has been loaded from storage or retrieved from a peer (wh
```suggestion
These two methods return the current state of the document. `doc()` is an asynchronous method that resolves when a repository loads the document from storage or retrieves it from a peer (whichever happens first), and `docSync()` is a synchronous method that assumes the document is already available.
The examples below illustrate asynchronously loading a document or synchronously loading a document and then interacting with it:
```

2023-11-06 18:38 UTC, heckj commented on blog/2023-11-06-automerge-repo.md
> +In this latter example we use `DocHandle.whenReady`, which returns a promise which resolves when the document has either been loaded from storage or fetched from another peer in the network.
```suggestion
In this latter example we use `DocHandle.whenReady`, which returns a promise that the repository resolves when it loads a document from storage or fetches it from another peer in the network.
```

2023-11-06 18:38 UTC, heckj commented on blog/2023-11-06-automerge-repo.md
> +`DocHandle.change` allows you to modify a document.
```suggestion
Use `DocHandle.change` when you modify a document.
```

2023-11-06 18:38 UTC, heckj commented on blog/2023-11-06-automerge-repo.md
> +`automerge-repo` provides a set of primitives that you can use to build a wide range of applications. To make this easier, we have built integrations with a few common UI frameworks (and you can easi
Do you want to "welcome further integrations" here (as in pull-requests for additional integrations), or is the intention that as a developer, build it and use it yourself?

2023-11-06 18:38 UTC, heckj commented on blog/2023-11-06-automerge-repo.md
> +[`@automerge/automerge-repo-react-hooks`](https://www.npmjs.com/package/@automerge/automerge-repo-react-hooks) makes it easy to use `automerge-repo` in a React application. Once you've constructed a
```suggestion
[`@automerge/automerge-repo-react-hooks`](https://www.npmjs.com/package/@automerge/automerge-repo-react-hooks) makes it easy to use `automerge-repo` in a React application. Once you've constructed a `Repo` you can make it available to your React application using [`RepoContext`](https://automerge.org/automerge-repo/variables/_automerge_automerge_repo_react_hooks.RepoContext.html). Once available, call `useHandle` to obtain a `DocHandle`:
```

2023-11-06 18:38 UTC, heckj commented on blog/2023-11-06-automerge-repo.md
> +Note that when changes are received over the network or made locally, the old Automerge document remains immutable, and any modified parts of the document get new objects. This means that React will
```suggestion
Note that when `Repo` receives changes over the network or registers local changes, the original Automerge document remains immutable, and any modified parts of the document get new objects. This means that React will only re-render the parts of the UI that depend on a part of the document that has changed.
```

2023-11-06 18:38 UTC, heckj commented on blog/2023-11-06-automerge-repo.md
> +A storage adapter represents some kind of backend that will be used to store the data in a repo. Storage adapters can be implemented for any key/value store that allows you to query a range of keys w
```suggestion
A storage adapter represents some kind of backend that stores the data in a repo. Storage adapters can be implemented for any key/value store that allows you to query a range of keys with a given prefix. There is no concurrency control required (that's implemented in `automerge-repo`) so you can safely have multiple repos pointing at the same storage. For example, you could implement an adapter on top of Redis.
```

2023-11-06 18:38 UTC, heckj commented on blog/2023-11-06-automerge-repo.md
> +There are already storage adapters for IndexedDB and the file system (on Node).
```suggestion
The `automerge-repo` library provides storage adapters for IndexedDB and the file system (on Node).
```

2023-11-06 18:38 UTC, heckj commented on blog/2023-11-06-automerge-repo.md
> +A network adapter represents a way of connecting to other peers. Network adapters raise events when a new peer is discovered or when a message is recieved, and they implement a `send` method for tran
```suggestion
A network adapter represents a way of connecting to other peers. Network adapters raise events when a new peer is discovered or when a message is recieved, and implement a `send` method for transmitting messages to another peer. `automerge-repo` assumes a reliable, in-order transport for each peer; as long as you can provide this (e.g. using a TCP connection), you can implement an adapter. You could implement an adapter for [BLE](https://en.wikipedia.org/wiki/Bluetooth_Low_Energy), for example.
```

2023-11-06 18:38 UTC, heckj commented on blog/2023-11-06-automerge-repo.md
> +There are already network adapters for WebSocket, MessageChannel, and BroadcastChannel.
```suggestion
The `automerge-repo` library provides network adapters for WebSocket, MessageChannel, and BroadcastChannel.
```

2023-11-06 18:38 UTC, heckj commented on blog/2023-11-06-automerge-repo.md
> +This release of `automerge-repo` is just for javascript. Automerge is a multi-language library though and there are efforts under way to implement `automerge-repo` on other platforms. The most mature
```suggestion
This release of `automerge-repo` is just for javascript. Automerge is a multi-language library though and there are efforts under way to implement `automerge-repo` on other platforms. The most mature of these is [`automerge-repo-rs`](https://github.com/automerge/automerge-repo-rs). We welcome contributions and please reach out if you're starting to develop `automerge-repo` for a new platform.
```

2023-11-07 14:16 UTC, ept commented
👍 to @heckj's suggestions

2023-11-07 14:34 UTC, alexjg commented
Thanks @heckj! I think I've incorporated everything you suggested, it's much clearer!

2023-11-07 16:29 UTC, heckj approved these changes

2023-11-08 16:58 UTC, merged